### ISSUE TITLE
 xfce4-whiskermenu-plugin is missing

### ISSUE THREAD

**Issue by dreamyukii** [ublue-os/vauxite#14]
i prefer to use whisker menu than default xfce4 menu and its not available on base image

**Comment by hyperreal64** [comment]
The base image is supposed to contain a basic set of Xfce packages and attempts to reflect the default Fedora Xfce experience. The whiskermenu plugin is not part of that, so I don't see a reason to include it in the base image.

You can, however, layer the package with `rpm-ostree install xfce4-whiskermenu-plugin`.

**Comment by hyperreal64** [comment]
> i prefer to use whisker menu than default xfce4 menu and its not available on base image

So I checked out the regular Fedora Xfce spin in a VM and it looks like there are a number of panel plugins installed on the live ISO by default, including the whiskermenu plugin, so I will include some of those in the Vauxite base image. 

If there is a plugin or app that I haven't included in the Vauxite base image, and it's installed on the default Fedora Xfce spin, I will include it in the base image upon user request.

You should be able to upgrade to the latest Vauxite build in about 1-2 hours from now, which will have the xfce4-whiskermenu-plugin.
